name: tstore
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

# ------- PACKAGES ------- #
dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: null
  get_storage: ^2.1.1
  http: null
  iconsax: null
  intl: ^0.19.0
  logger: ^2.0.2+1
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_lints: ^2.0.0

  flutter_native_splash: null
  flutter_test:
    sdk: flutter

native_splash:
  color: "#FFFFFF"
  color_dark: "#272727"
  image: assets/logos/logo_lightmide.png
  image_dark: assets/logos/logo_darkmode.png

  android_12:
    color: "#FFFFFF"
    color_dark: "#272727"
    image: assets/logos/logo_lightmide.png
    image_dark: assets/logos/logo_darkmode.png

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/onBoarding/
    - assets/logos/
    - assets/images/animations/
    - assets/icons/categories/
    - assets/images/banners/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
