// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA80BANKK63ditBHZdvx9ELaCe_-v4u8Kw',
    appId: '1:136965152752:web:008ba31953288759790735',
    messagingSenderId: '136965152752',
    projectId: 'tstore-97188',
    authDomain: 'tstore-97188.firebaseapp.com',
    storageBucket: 'tstore-97188.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnSEjkw4L4_HHiT2LE4SICCnD-PlmqIHg',
    appId: '1:136965152752:android:2b3b35a025059818790735',
    messagingSenderId: '136965152752',
    projectId: 'tstore-97188',
    storageBucket: 'tstore-97188.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtmlp43983yWzWgGQwqWCOw2C4VNavftM',
    appId: '1:136965152752:ios:8988b53dc59e7eae790735',
    messagingSenderId: '136965152752',
    projectId: 'tstore-97188',
    storageBucket: 'tstore-97188.appspot.com',
    androidClientId: '136965152752-un5iq7nb7edfk3coi80opt74d82qidfk.apps.googleusercontent.com',
    iosClientId: '136965152752-b9d6rfgvn9stippd9niv0lpm6suflr0c.apps.googleusercontent.com',
    iosBundleId: 'com.example.tstore',
  );
}
